### ISSUE TITLE
Just a small review

### ISSUE THREAD

**Issue by buddh4** [GreenMeteor/humhub-weather-module#11]
Hi, 

just a small review / feedback from my side.

- The new version check is not really common for marketplace modules, and seems to me a bit too much for a small module like this. It would be better to integrate such a logic in the core and check for all marketplace updates in one call. Also, it makes the codebase of the module way more complex as it needs to be.

- You should always prefix your table names with your module id and perhaps your project name in order to prevent conflicts:

Instead of:
```
public static function tableName()
{
    return 'log';
}
```

Use e.g.:
```
public static function tableName()
{
    return 'greenmeteor_weather_log';
}
```

- The same goes for namespaces. You should choose a namespace like:

`greenmeteor/humhub/modules/weather`

- The following classes do not seem to really be used:

- `humhub\modules\weather\notifications\Log` class is not in use
- `humhub\modules\weather\notifications\WeatherNotificationCategory`

**Comment by ArchBlood** [comment]
We'll work on implementing such a thing, thanks for the review!

**Comment by ArchBlood** [comment]
As for the classes not being used, we noticed this as well, we were planning on removing them, we just wanted to test out if we could get notifications on new version updates, so far they do work, but not all the time it would seem, as when there is a new update to the module published it also sends a second notification for the core of HumHub being updated, so we'll more than likely be removing this in favor hoping such a function will be implemented into the core of HumHub.

**Comment by ArchBlood** [comment]
The class for `WeatherNotificationCategory` is required in the NewVersionAvailable.php file on [line 55](https://github.com/GreenMeteor/humhub-weather-module/blob/master/notifications/NewVersionAvailable.php#L55), this of course was implemented similar to how the admin core module has it setup, but seems we failed slightly, as for the Log class, this was required by the `CleanupLog` job.

All in all the notification function works but will need to be removed as it also throws our code checking out of our coding standards. :thinking:

**Comment by ArchBlood** [comment]
We have removed the notification function from the module at this time but will keep it in our dev branch of this repo just for testing purposes.
