### ISSUE TITLE
Display using user language ?

### ISSUE THREAD

**Issue by michael-barchy-cpasbxl** [GreenMeteor/humhub-weather-module#17]
How do you display the weather using the user's language ?

**Comment by ArchBlood** [comment]
Originally if you direct to the given URL there is a parameter in the URL that deals with local language `/en/` was set as the default so I wouldn't be surprised if just changing the parameter for a different location would work in this case as well but there would have to be tests done beforehand :sweat_smile:

### Example
English language
`https://forecast7.com/en/40d71n74d01/new-york`
Spanish language
`https://forecast7.com/es/40d71n74d01/new-york`

**Comment by ArchBlood** [comment]
As for displaying it universally, this isn't possible with out complex and function breaking that this could be with how we've implemented the module, in the future we may try adding this to the premium version of this module but this is not currently on our to-do list

**Comment by michael-barchy-cpasbxl** [comment]
So, I achieved this using a "very complex" code 🤣 

WeatherFrame.php

add this 
        `$url  = str_replace('{language}', Yii::t('WeatherModule.base', '{language}'), $url);`
after
        `$url = Yii::$app->getModule('weather')->getServerUrl() . '';`

in messages folder, add a `{language}` key in `base.php` for each language: e.g. `"{language}" => "en"` in
en-US folder, `"{language}" => "fr"` in fr folder, etc.

Hope it helps others 😉 

[weather.zip](https://github.com/GreenMeteor/humhub-weather-module/files/5259684/weather.zip)

**Comment by ArchBlood** [comment]
> So, I achieved this using a "very complex" code 
> 
> WeatherFrame.php
> 
> add this
> `$url = str_replace('{language}', Yii::t('WeatherModule.base', '{language}'), $url);`
> after
> `$url = Yii::$app->getModule('weather')->getServerUrl() . '';`

Sadly I wouldn't recommend using the translation overwrite option here as there are no translations being done just a hackish way of changing the parameter, the more suitable way of doing this would be

```php
$url  = str_replace('{language}', Yii::$app->language, $url);
```
`{language}` being the language parameter being replaced with the user's default `Yii::$app->language`

### Example
Using this `https://forecast7.com/{language}/40d71n74d01/new-york/` then would change based on the default language they pick from their account settings without having to do any message tampering, only issue would be for English users where HumHub uses `en_US` and `en_GB` not `en` the widget will not display, but you can easily make exceptions for some languages in this case :man_shrugging:

**Comment by michael-barchy-cpasbxl** [comment]
`$url  = str_replace('{language}', substr(Yii::$app->language, 0, 2), $url);`

**Comment by ArchBlood** [comment]
If you wouldn't mind creating a p/r that would make things a lot faster on implementing as I'm on mobile right now and doing anything code wise on mobile sucks :sweat_smile:
