### ISSUE TITLE
Difference between Free and Premium Module?

### ISSUE THREAD

**Issue by buddh4** [GreenMeteor/humhub-weather-module#19]
Just wanted to know whats the difference between the free and premium version? They share the same description/documentation.

**Comment by ArchBlood** [comment]
The main difference is the use case sadly, the "free" version is more used globally, whereas the premium version is used between different spaces as well as the dashboard default, we had also planned on adding other services because of #14 but haven't had the time to do this :thinking:

**Comment by ArchBlood** [comment]
As for the description/documentation kind of got lazy on this which is probably why :sweat_smile:

**Comment by ArchBlood** [comment]
Ideally they both do the same thing just differently and give the space operator (Admin) the option to enable it on space level with a different widget displayed per-space as well as different from the dashboard default

**Comment by buddh4** [comment]
kk, just wanted to ask since we should not pollut the marketplace with duplicates, would be great if you could align the documentation and point out the differences.

**Comment by ArchBlood** [comment]
I'll make sure that is done in the next release for both versions

**Comment by ArchBlood** [comment]
Just placing this here as a check list
- [x] [Premium Weather](https://www.humhub.com/en/marketplace/premium_weather/) module
- [ ] [Free Weather module](https://www.humhub.com/en/marketplace/weather/)

**Comment by ArchBlood** [comment]
Closing [v1.1.1](https://github.com/GreenMeteor/humhub-weather-module/releases/tag/v1.1.1)
