### ISSUE TITLE
Add GDPR information

### ISSUE THREAD

**Issue by buddh4** [GreenMeteor/humhub-weather-module#20]
Since this module uses and communicates with external services ( https://weatherwidget.io/, https://forecast7.com), you should add some information regarding General Data Protection Regulation (GDPR). Users may not be aware of this.

Ah sorry did not see `Note: Forecast7 is an external service that provides the code that is placed within your HumHub's sidebar.` Perhaps we should create a template text for all modules which may be affected and link to the legal module?

**Comment by buddh4** [comment]
The question is also. If you run an open network with guest access. Users can not decline this.

**Comment by ArchBlood** [comment]
That would be a great idea! Ideally GDPR can defiantly cause issues with modules that piggyback from third-party code such as this module and discordapp/premium_discord/premium_weather so adding a template text for modules within the legal module would be helpful in the future

**Comment by buddh4** [comment]
We'll discuss this internally and maybe add something to the docs, as a suggestion I'd add the two urls I mentioned to the gdpr note of the module.
